# Para saber componer las opciones correctamente en TOML en la tecnolog√≠a Besu se ha utilizado
# en el siguiente enlace:
# https://besu.hyperledger.org/public-networks/reference/cli/options

# Node 1 configuration
min-gas-price=0

# Hecho por mi para la tabla [Node]

data-path="/var/lib/besu/QBFT-Network/Node/data" #The path to the Besu data directory. 
#The default is the directory you installed Besu in, or /opt/besu/database if using the Besu Docker image.
p2p-port="30303"
p2p-host="0.0.0.0"

#Lo que ha hecho cursor
#[Node]
#Name = "Node1"
#DataPath = "/opt/besu/Node-1/data"
#Host = "0.0.0.0"
#P2PPort = ${NODE1_P2P_PORT}

# Hecho por mi para la tabla [RPC]
rpc-http-enabled=true
rpc-http-host="0.0.0.0" #To allow remote connections, set to 0.0.0.0.
rpc-http-port="8545" #The port (TCP) on which HTTP JSON-RPC listens. The default is 8545
rpc-ws-enabled=true #Enables or disables the WebSocket JSON-RPC service. The default is false
rpc-ws-host="0.0.0.0" #To allow remote connections, set to 0.0.0.0
rpc-ws-port="8546" #The port (TCP) on which WebSocket JSON-RPC listens. The default is 8546
rpc-http-api=["ADMIN","DEBUG","MINER","ETH","TXPOOL","NET","TRACE","WEB3","PRIV","PLUGINS","QBFT"]
rpc-http-cors-origins=["all"] # A list of domain URLs for CORS validation. Listed domains can access the node using JSON-RPC. If your client interacts with Besu using a browser app (such as Remix or a block explorer), add the client domain to the list.
# The default value is "none". If you do not list any domains, browser apps cannot interact with your Besu node.


#Lo que ha hecho cursor
#[RPC]
#HttpEnabled = true
#HttpHost = "0.0.0.0"
#HttpPort = ${NODE1_RPC_HTTP_PORT}
#WsEnabled = true
#WsHost = "0.0.0.0"
#WsPort = ${NODE1_RPC_WS_PORT}

# Hecho por mi para la tabla [Network]
network-id="1" # The P2P network identifier.
# Use this option to override the default network ID. The default value is the same 
# as the chain ID defined in the genesis file.


#Lo que ha hecho cursor
# [Network]
# ID = ${NETWORK_ID}

# Hecho por mi para la tabla [Genesis]
genesis-file="/var/lib/besu/QBFT-Network/networkFiles/genesis.json"

#Lo que ha hecho cursor
# [Genesis]
# Path = "/opt/besu/genesis.json"

# Hecho por mi para la tabla [Metrics]
metrics-enabled=true
 # Enables or disables the metrics exporter. The default is false.
#To enable the Prometheus monitoring and alerting service to access Hyperledger Besu metrics,
#use the --metrics-enabled option.
metrics-host="127.0.0.1" #The host on which Prometheus accesses Besu metrics. The metrics server respects the --host-allowlist option.
#The default is 127.0.0.1.
metrics-port=9545 #The port (TCP) on which Prometheus accesses Besu metrics. The default is 9545. Ports must be exposed appropriately

#Lo que ha hecho cursor
# [Metrics]
# Enabled = false

# Hecho por mi para la tabla [Privacy]
privacy-enabled=false #Enables or disables private transactions. The default is false.
# Esta ultima variable es parte de "Private networks" https://besu.hyperledger.org/private-networks/concepts/privacy#privacy-enabled-networks

host-allowlist=["*"]

# bootnodes
bootnodes=["enode://833450ee13c9508967e1d7f2a82b716ae20895f890573b3128c84665986cd72d0eba3de69d642bab697b10edbd61f0369a35969aef34919c1368c1b88bd12f0b@172.16.0.1:30303","enode://7da7bb3bd6a5065d0082b80787f34f56e16c79f1d1c23b43a6931625cf85ed3a2320eaa6df1c832f8e266d49249c0636f937ae3b86d68a1a0ed533e9609db09c@172.16.0.2:30303","enode://c8a84152fb001994ef7320192a5abe548c53db10468fef61e418e7b100a0c5b49607b6e8cfde66b837d92f4b41eb9b705f77a637dcef326693dd38a6322b8b25@172.16.0.3:30303","enode://ee5651536dc98d2d4adab5f4dd6aaa639ba67236dd8c74387208ba5c1b20a381f782076d71eda1b1efa79c4dd66d53cc92a24cdd57da3b93824b41cd1c537dcf@172.16.0.4:30303"]

# Discovery at boot is set to a list of static files, but will also discover new nodes should they be added
# static nodes
static-nodes-file="/var/lib/besu/QBFT-Network/networkFiles/static-nodes.json"
discovery-enabled=true
